### ISSUE TITLE
This video is private? 

### ISSUE THREAD

**Issue by andiconda** [youngwoo-yoon/youtube-gesture-dataset#5]
hi thank you for your last answer. it is very helpful.

what is the solution? 
ERROR: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 2146, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download_video.py", line 220, in <module>
    main()
  File "download_video.py", line 204, in main
    download(vid_list)
  File "download_video.py", line 137, in download
    info = ydl.extract_info(url, download=False)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.

**Comment by youngwoo-yoon** [comment]
I have not encountered this error. I think some videos are deleted or private. Removing those video ids from "video_ids.txt" will be the easiest solution. You can also add some code to handle the exception.

**Comment by andiconda** [comment]
yes, as you said. it works.
thank you very much.
